repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_fmt
        args: [--args=--chdir=terraform]
      - id: terraform_tflint
        args: [--args=--chdir=terraform]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: ^tools/.*\.sh$
